name: Astronomer CI - Create preview Deployment

on:
  create:
    branches:
    - "**"

env:
  ## Set your Workspace API key token as a GitHub secret
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create preview Deployment
      uses: astronomer/deploy-action@v0.3
      with:
        action: create-deployment-preview
        deployment-id: cli235ha969559lyxh3fdchwxr
