name: Astronomer CI - Deploy code to preview

on:
  pull_request:
    branches:
      - main

env:
  ## Set your Workspace API key token as a GitHub secret
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy code to preview
      uses: astronomer/deploy-action@v0.2
      with:
        action: deploy-deployment-preview
        deployment-id: clgqlmjuj1188271juwdtv1t8za